### ISSUE TITLE
Rotation tool is broken

### ISSUE THREAD

**Issue by 6ixfalls** [Windows81/The-Fruitful-Labours-of-the-Visual-Roblox-Plugin-of-Respected-Leader-VisualPlugin-the-Prolific#1]
When trying to rotate a group of parts or a part, it bugs out and returns to its original orientation.

**Comment by Windows81** [comment]
Thank you for your feedback.  I've looked into it and discovered it's a bug with the `RotationHandles` object where the `MouseButton1Up` hasn't been firing properly.  I should have a workaround in place within the next 666 days.

**Comment by Windows81** [comment]
Thank you for bringing this issue up.  Feel free to bring anything of concern in the future.  I have published [this release](https://github.com/Windows81/The-Fruitful-Labours-of-the-Visual-Roblox-Plugin-of-Respected-Leader-VisualPlugin-the-Prolific/releases/tag/0.1.2.3.4.5.6.7.8.9) to follow up with it, but you can always download the source code from the main page.
